### ISSUE TITLE
black screen 

### ISSUE THREAD

**Issue by shaeon** [gyurco/Next186#15]
Hi,

I synthesized your core for SIDI after fix some missing file and i got a black screen. Also i sent to a friend mist core file and he tried on mist also he got when file.

Am i doing something wrong? I read maybe this core need inverted sync?

Best regards

**Comment by gyurco** [comment]
It's hard to tell from this description. I would assume you didn't use the correct BIOS ROM.

**Comment by shaeon** [comment]
If i got a commint from 2021 year the core is working. Here its the ROM that I have in root of SD and this ROM with old core versión are working fine. 

After I load last core yellow light its on all time.

[Next186.zip](https://github.com/gyurco/Next186/files/9554750/Next186.zip)

**Comment by shaeon** [comment]
You are right! :) I changed ROM and I got new menu! :)

Thanks Gyurco!
