### ISSUE TITLE
Upgrade Tandy Sound to JT89

### ISSUE THREAD

**Issue by spark2k06** [gyurco/Next186#17]
Recently, I upgraded the Tandy sound to JT89 in PCXT core for MiSTer, which is more accurate than Arnim Laeuger, or at least it sounds much better, especially the percussions.

https://github.com/jotego/jt89

You may also be interested in upgrading... here are the differences:

[SN76489AN Compatible Implementation by Arnim Laeuger](https://soundcloud.com/aitor-gomez-7/sn76489an-compatible-implementation-by-arnim-laeuger/s-ZD2R4M9stIU?si=fd3771642818473b83a469357b85c76e&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing)

[JT89 by jotego](https://soundcloud.com/aitor-gomez-7/jt89-by-jotego/s-A2lrZljRJg0?si=fd3771642818473b83a469357b85c76e&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing)

**Comment by gyurco** [comment]
For me, both sounds good :)
I assumed jt89 is for SMS/Genesis, which has a slightly different noise generator.

**Comment by spark2k06** [comment]
I understand, I close the case then ;-)
