### ISSUE TITLE
Adlib not recognized at certain CPU speeds

### ISSUE THREAD

**Issue by alessioscand** [gyurco/Next186#3]
Hi,
it seems that Adlib is not always recognized at certain CPU speeds. Some examples:
- in KINGS OF THE BEACH and STELLAR 7 at maximum CPU speed there is no music on the title screen, but with /3 it plays correctly (Adlib).
- SPEEDBALL 2 (after Setup) does not recognize any Adlib device at maximum speed, but it runs correctly in /3.
- on the other hand, in ARKANOID REVENGE OF DOH Adlib works at maximum speed, but the game is too fast. With /3 CPU the gameplay speed is OK but no more Adlib.
Thank you.

**Comment by squidrpi** [comment]
Yes I've had that problem on some Monkey 1, 2 and Atlantis occassionally, i.e. no music plays. Switching the speed didn't help.

**Comment by alessioscand** [comment]
It seems that Adlib detection is picky with fast CPUs also in DOSbox and real hardware:
https://www.vogons.org/viewtopic.php?t=21530

So maybe this issue is not specific to Next186 core (pardon! but Arkanoid behaviour remains strange).

**Comment by gyurco** [comment]
It's not uncommon to see bad behaviour on fast hardware. Divide errors at start for example also happens on too fast machines.

**Comment by alessioscand** [comment]
OK, the CPU speed option is much important for compatibility. So I can close the issue (pardon again).
