### ISSUE TITLE
Sound Source not detected in Hocus Pocus

### ISSUE THREAD

**Issue by alessioscand** [gyurco/Next186#4]
Hi,
Hocus Pocus (shareware) runs almost perfectly, but the Disney Sound Source audio device, supported in the Setup, it's not detected at all.
Thank you.

**Comment by alessioscand** [comment]
Maybe these links could be useful?

https://www.vogons.org/viewtopic.php?t=40751

https://archive.org/details/dss-programmers-guide/page/n3/mode/2up

Thanks

**Comment by gyurco** [comment]
Looks like they need more precise FIFO emptying procedure. I'm not sure if it's easy to fix this. Many things in this core is "compatible" but not the replica of an existing hardware. Don't expect ST like compatibility.

**Comment by alessioscand** [comment]
I understand, but I'm not sure that this is effectively related also to Hocus Pocus (I'm not a developer).
Of course I've tested all the different CPU speed options with no luck.

**Comment by alessioscand** [comment]
OK, as mentioned here:

https://twitter.com/volkertb/status/1177340587558809606?s=19

It seems that Next186 core implements a simplified "clone" of the Covox Speech (Stereo-on-1) and not a full fledged Disney Sound Source.
So, again, it's not a real issue of the core, nevertheless I'd like to leave it open for a while, hoping for a full FPGA DSS implementation (schematics are available), a driver or simply a patch for the game executable. Thanks!

**Comment by gyurco** [comment]
It's DSS, but with a slightly increased sampling rate (44100 Hz/6 = 7350 Hz). What causes detection issues? Don't know without debugging.

**Comment by alessioscand** [comment]
> What causes detection issues? Don't know without debugging.

Hoping it will help, I opened a topic on VOGONS:
https://www.vogons.org/viewtopic.php?f=62&t=82650&e=1&view=unread#unread

**Comment by alessioscand** [comment]
Good news! (I hope)

> Full algorithm in the shareware version (installed) as distributed DOS games archive:
> Deassert /INIT on the printer port (write 04 to the control register)
> Wait for four timer ticks at 140Hz (I guess to drain the FIFO)
> Test that ACK reads as zero
> Strobe 32736 data bytes as fast as possible into the DSS (likely a bug, and intended to be 32 bytes). Strobing is done by temporarily pulsing SELECT IN high (writing 0C to the control register, than writing 04 again). If you supply the parameter "sst" (sound source stereo?), not only SELECT IN, but AUTOFEED is pulsed too.
> Test that ACK reads as one
> If both tests for ACK succeed, the sound source is detected. Note that the initialization part depends on timing, whereas the actual FIFO testing part does not.

...and

>  You can run HOCUS.EXE (the shareware version) with the parameters ss1, ss2 or ss3 to force sound source detection at ports 3BC, 378 and 278 respectively, circumventing the auto-detection mechanism.

I'll test the parameters ASAP.

**Comment by alessioscand** [comment]
DSS works perfectly in Hocus Pocus with the /ss2 parameter! I close the issue!

**Comment by gyurco** [comment]
Good!
